# Generated by Django 4.2.2 on 2023-06-08 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_team_alter_team_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='member',
            field=models.ManyToManyField(blank=True, null=True, related_name='teams', through='task.Membership', to='task.member'),
        ),
    ]
