# Generated by Django 4.2.2 on 2023-06-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_team_alter_team_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='teams', through='task.Membership', to='task.member'),
        ),
    ]
