# Generated by Django 4.2.2 on 2023-06-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamname',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
