# Generated by Django 4.2.2 on 2023-06-09 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_membership_member_alter_team_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='member',
        ),
    ]
