# Generated by Django 4.2.2 on 2023-06-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_remove_team_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamname',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
