# Generated by Django 4.2.2 on 2023-06-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_alter_membership_member_alter_membership_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/note.jpg', upload_to='images/'),
        ),
    ]
