# Generated by Django 4.2.2 on 2023-06-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_alter_task_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='thumbnail',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dkip8l8nh/image/upload/v1686624957/lp59ywlxdq2xf1fvay3h.jpg', upload_to='images/'),
        ),
    ]
