# Generated by Django 4.2.2 on 2023-06-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_alter_task_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='thumbnail',
            field=models.ImageField(blank=True, default='https://www.pngall.com/wp-content/uploads/8/Task-PNG-Free-Download.png', upload_to='images/'),
        ),
    ]
