# Generated by Django 4.2.2 on 2023-06-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_alter_task_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='thumbnail',
            field=models.ImageField(blank=True, default='https://i.pinimg.com/564x/ec/04/14/ec0414fdaf5779ac6162a865f9d71db1.jpg', upload_to='images/'),
        ),
    ]
